# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
dist: goreleaser-dist

builds:
  - id: &bin clippy-shim
    builder: rust
    binary: *bin
    tool: cargo
    command: zigbuild
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-pc-windows-gnullvm
    flags: ["--release", "--package=clippy-shim"]

archives:
  - id: *bin
    ids: [*bin]
    formats: ["tar.gz"]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files: [LICENSE]
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  filters:
    exclude: ["^ci:", "^docs:", "^test:"]

homebrew_casks:
  - name: *bin
    ids: [*bin]
    description: "A tiny shim around cargo clippy."
    custom_block: |
      os macos: "darwin", linux: "linux"

      postflight_steps do
        on_macos do
          if_path_exists "/usr/bin/xattr" do
            run "/usr/bin/xattr",
                args:         ["-dr", "com.apple.quarantine", "{{ `{{staged_path}}` }}/clippy-shim"],
                must_succeed: false
          end
        end
      end
    directory: Casks
    commit_author:
      name: romnn
      email: contact@romnn.com
    repository:
      owner: romnn
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: false

release:
  draft: false
